name: Hauling Data Scraper

on:
  schedule:
    - cron: '0 * * * *'     # Runs every hour at the top of the hour
    - cron: '50 23 * * *'   # Runs at 6:50 AM WIB (23:50 UTC)
  workflow_dispatch:        # Gives you a manual "Run" button to test it

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Grants the server permission to save the file back to your repo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Execute Scraper
        run: python scraper.py

      - name: Commit and Push Data
        run: |
          git config user.name "Scraper Bot"
          git config user.email "actions@users.noreply.github.com"
          git add hauling_data_*.csv
          # If there is no new data, git commit will fail. The || exit 0 prevents the workflow from crashing.
          git commit -m "Automated data backup" || exit 0
          git push
